last_change = 2026-09-29T14:52:08.445958Z
addr = 0x14d570
size = 0x3
name = "IGameSystem_OnClientPostAdvanceTick"

[header]
name = "IGameSystem_OnClientPostAdvanceTick"
addr = 0x14d570

[header.args]
