last_change = 2026-09-29T14:52:21.758324Z
addr = 0x355320
size = 0x15f
name = "IGameSystem_Add"
type = "long long"

[header]
name = "IGameSystem_Add"
addr = 0x355320
type = "long long"

[header.args]
