last_change = 2026-09-29T14:52:08.446018Z
addr = 0x9c09c0
size = 0x1dd
name = "CGameEntitySystem_ctor"
type = "long long"

[header]
name = "CGameEntitySystem_ctor"
addr = 0x9c09c0
type = "long long"

[header.args]
