last_change = 2026-09-29T14:52:24.510286Z
addr = 0xb6bf80
size = 0x109
name = "CClientInput_CreateMove"
type = "void"

[header]
name = "CClientInput_CreateMove"
addr = 0xb6bf80
type = "void"

[header.args]
