last_change = 2026-09-29T14:52:08.446122Z
addr = 0xb84d60
size = 0x85
name = "CAM_Command_CommandHandler"
type = "long long"

[header]
name = "CAM_Command_CommandHandler"
addr = 0xb84d60
type = "long long"

[header.args]
