last_change = 2026-09-29T14:52:08.446132Z
addr = 0xc17140
size = 0x306
name = "CViewRender_Render"
type = "long long"

[header]
name = "CViewRender_Render"
addr = 0xc17140
type = "long long"

[header.args]
