last_change = 2026-09-29T14:52:25.463377Z
addr = 0xf8e790
size = 0x179
name = "GameStateAPI_GetAccoladeLocalizationString"
type = "char *"

[header]
name = "GameStateAPI_GetAccoladeLocalizationString"
addr = 0xf8e790
type = "char *"

[header.args]
