last_change = 2026-09-29T14:52:08.446162Z
addr = 0xf8f7d0
size = 0x6a
name = "GameStateAPI_GetCSGOGameUIStateName"
type = "const char *"

[header]
name = "GameStateAPI_GetCSGOGameUIStateName"
addr = 0xf8f7d0
type = "const char *"

[header.args]
