last_change = 2026-09-29T14:52:08.446169Z
addr = 0xf92b60
size = 0x9f
name = "GameStateAPI_GetCoachingTeamNumber"
type = "long long"

[header]
name = "GameStateAPI_GetCoachingTeamNumber"
addr = 0xf92b60
type = "long long"

[header.args]
