last_change = 2026-09-29T14:52:26.315474Z
addr = 0xfa0400
size = 0xf2
name = "GameStateAPI_GetLocalOrInEyePlayerXuid"
type = "char *"

[header]
name = "GameStateAPI_GetLocalOrInEyePlayerXuid"
addr = 0xfa0400
type = "char *"

[header.args]
