last_change = 2026-09-29T14:52:08.446218Z
addr = 0xfa9cf0
size = 0xd1
name = "GameStateAPI_GetPlayerCommendsFriendly"
type = "long long"

[header]
name = "GameStateAPI_GetPlayerCommendsFriendly"
addr = 0xfa9cf0
type = "long long"

[header.args]
