last_change = 2026-09-29T14:52:08.446264Z
addr = 0xfad440
size = 0x47
name = "GameStateAPI_GetPlayerVoiceVolume"
type = "void"

[header]
name = "GameStateAPI_GetPlayerVoiceVolume"
addr = 0xfad440
type = "void"

[header.args]
