last_change = 2026-09-29T14:52:08.446266Z
addr = 0xfad490
size = 0xac
name = "GameStateAPI_GetPlayerXpLevel"
type = "long long"

[header]
name = "GameStateAPI_GetPlayerXpLevel"
addr = 0xfad490
type = "long long"

[header.args]
