last_change = 2026-09-29T14:52:08.446194Z
addr = 0xfa3980
size = 0x20
name = "GameStateAPI_GetMapName"
type = "long long"

[header]
name = "GameStateAPI_GetMapName"
addr = 0xfa3980
type = "long long"

[header.args]
