last_change = 2026-09-29T14:52:28.210243Z
addr = 0xfab7e0
size = 0x13f3
name = "GameStateAPI_GetPlayerStatsJSO"
type = "unsigned long long **"

[header]
name = "GameStateAPI_GetPlayerStatsJSO"
addr = 0xfab7e0
type = "unsigned long long **"

[header.args]
