last_change = 2026-09-29T14:52:08.446280Z
addr = 0xfb53d0
size = 0x3a
name = "GameStateAPI_GetTeamLivingPlayerCount"
type = "long long"

[header]
name = "GameStateAPI_GetTeamLivingPlayerCount"
addr = 0xfb53d0
type = "long long"

[header.args]
