last_change = 2026-09-29T14:52:08.446294Z
addr = 0xfb8700
size = 0xd3
name = "GameStateAPI_HasCommunicationAbuseMute"
type = "bool"

[header]
name = "GameStateAPI_HasCommunicationAbuseMute"
addr = 0xfb8700
type = "bool"

[header.args]
