last_change = 2026-09-29T14:52:08.446314Z
addr = 0xfcb5c0
size = 0x103
name = "GameStateAPI_IsLocalPlayerWatchingOwnDemo"
type = "char"

[header]
name = "GameStateAPI_IsLocalPlayerWatchingOwnDemo"
addr = 0xfcb5c0
type = "char"

[header.args]
