last_change = 2026-09-29T14:52:08.446348Z
addr = 0xfee6c0
size = 0x48
name = "GameStateAPI_SetPlayerVoiceVolume"
type = "long long"

[header]
name = "GameStateAPI_SetPlayerVoiceVolume"
addr = 0xfee6c0
type = "long long"

[header.args]
