last_change = 2026-09-29T14:52:08.446343Z
addr = 0xfecde0
size = 0xd5
name = "GameStateAPI_SetCasterIsCameraman"
type = "long long"

[header]
name = "GameStateAPI_SetCasterIsCameraman"
addr = 0xfecde0
type = "long long"

[header.args]
