last_change = 2026-09-29T14:52:08.446338Z
addr = 0xfe23d0
size = 0x2f3
name = "GameStateAPI_QueryServersForCommendation"
type = "char"

[header]
name = "GameStateAPI_QueryServersForCommendation"
addr = 0xfe23d0
type = "char"

[header.args]
