last_change = 2026-09-29T14:52:08.446358Z
addr = 0xff7640
size = 0x238
name = "GameStateAPI_ToggleMute"
type = "long long"

[header]
name = "GameStateAPI_ToggleMute"
addr = 0xff7640
type = "long long"

[header.args]
