last_change = 2026-09-29T14:52:08.446354Z
addr = 0xff4f70
size = 0x284
name = "GameStateAPI_SubmitPlayerReport"
type = "unsigned long long"

[header]
name = "GameStateAPI_SubmitPlayerReport"
addr = 0xff4f70
type = "unsigned long long"

[header.args]
