last_change = 2026-09-29T14:52:08.446371Z
addr = 0x15deb00
size = 0xc7
name = "CNetworkSerializerBindingBuildFilter_GetFieldPriority"
type = "long long"

[header]
name = "CNetworkSerializerBindingBuildFilter_GetFieldPriority"
addr = 0x15deb00
type = "long long"

[header.args]
